# Generated by Django 3.1.5 on 2021-04-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
    ]
