# Generated by Django 3.1.5 on 2021-04-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210430_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='amplifire',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='amplifire',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='auxcable',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='auxcable',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='bluetoothdongle',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='bluetoothdongle',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='cameraglass',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='cameraglass',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='carplayer',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='carplayer',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='chargeradabter',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='chargeradabter',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='converter',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='converter',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='electricconverter',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='electricconverter',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='flashmemory',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='flashmemory',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='hcovers',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='hcovers',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='headset',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='headset',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='mobilebattery',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='mobilebattery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='mobilecovers',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='mobilecovers',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='modem',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='modem',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='monopadvsholder',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='monopadvsholder',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='screenglass',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='screenglass',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='sdcards',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='sdcards',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='tv',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
        migrations.AddField(
            model_name='tv',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
    ]
