# Generated by Django 3.1.5 on 2021-05-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210430_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilecovers',
            name='product',
        ),
    ]
