# Generated by Django 3.1.5 on 2021-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_mobilecovers_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeradabter',
            name='type',
            field=models.CharField(choices=[(1, 'normal'), (2, 'lighter')], default=1, max_length=9),
        ),
    ]
