# Generated by Django 3.1.5 on 2021-05-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20210505_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeradabter',
            name='type',
            field=models.CharField(choices=[('normal', 'normal'), ('lighter', 'lighter')], default=1, max_length=9),
        ),
    ]
