# Generated by Django 3.1.5 on 2021-05-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20210505_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='BrandEnglish',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
