# Generated by Django 3.1.5 on 2021-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_brand_brandenglish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenglass',
            name='FrontOrBack',
            field=models.CharField(blank=True, choices=[('front', 'front'), ('back', 'back')], default='1', max_length=10, null=True),
        ),
    ]
