# Generated by Django 3.1.5 on 2021-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20210510_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenglass',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='mouse',
            name='contact_type',
            field=models.CharField(choices=[('wire', 'wire'), ('bluetooth', 'bluetooth'), ('wifi', 'wifi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='gender',
            field=models.CharField(choices=[('آقایان', 'آقایان'), ('خانم ها', 'خانم ها'), ('آقایان و خانم ها', 'آقایان و خانم ها')], default='3', max_length=35),
        ),
    ]
